#Create Aeronautics Toolgun Client Settings
#Wed Jun 10 12:42:15 CDT 2026
autoWeldEnabled=false
bearingAxisMode=AUTO
bearingAxisVisualsEnabled=true
connectedSublevelProximity=0.5
connectionMode=FIXED
deleteRange=8
hudEnabled=true
magneticMarkersEnabled=true
nearbyQueryRange=0
offsetX=0
offsetY=0
offsetZ=0
panel=BLUEPRINTS
previewEnabled=true
rangeDeleteEnabled=false
rotationDegrees=75
rotationStep=15
scalePercent=100
selectedFile=native\:first_car.excraft
snapMode=FACE_CENTER
translateStep=0.25
weldAdjustStep=0.25
weldSelectionMode=FACE_POINTS
