#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jun 11 14:32:06 CDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
