#Universal Keyboard Settings
[keyboard]
	#Max wireless range in blocks between the keyboard and its linked target.
	#Events are dropped if the player exceeds this distance.
	#Set to greater than 2 million for range capable of reaching sub-levels
	#Range: 1–2147483647. Default: 32.
	# Default: 32
	# Range: > 1
	keyboardRange = 32
	#Duration in seconds for the Wireless Copycat test-face feature.
	#Applies to both the per-face Test button on the Copycat and the Locate button on the keyboard.
	#Range: 1–300. Default: 5.
	# Default: 5
	# Range: 1 ~ 300
	copycatLocateDuration = 5
	#Mark this option 'true' to start Live Controls immediately when you right-click keyboard
	#Live Controller menu must also be marked 'favorite'.
	#Shift-click the keyboard to open the main menu instead
	#Default: false.
	favoriteLiveControlAutoStart = false
